[project]
authors = ["anonymous"]
channels = ["conda-forge", "pytorch", "nvidia"]
description = "Add a short description here"
name = "cp_attack"
platforms = ["linux-64"]
version = "0.1.0"
channel-priority = "disabled"

[tasks]
opencood_setup = "python setup.py develop"
nms_gpu_build = "python opencood/utils/setup.py build_ext --inplace"
build_ssc = "cd dependencies/selective_scan && python setup.py develop"

[dependencies]
python = "3.8.*"
pytorch = ">=2.4.1,<3"
torchvision = ">=0.20.0,<0.21"
torchaudio = ">=2.4.1,<3"
pytorch-cuda = "12.*"
cmake = ">=3.30.5,<4"
easydict = "~=1.9"
numpy = ">=1.24.4,<2"
tqdm = ">=4.66.5,<5"
pyyaml = ">=6.0.2,<7"
einops = ">=0.8.0,<0.9"
scipy = ">=1.10.1,<2"
fvcore = ">=0.1.5.post20221221,<0.2"
packaging = ">=24.1,<25"
pytest = ">=8.3.3,<9"
chardet = ">=5.2.0,<6"
yacs = ">=0.1.8,<0.2"
termcolor = ">=2.4.0,<3"
submitit = ">=1.5.1,<2"
python-dateutil = ">=2.9.0,<3"
iopath = ">=0.1.10,<0.2"

[pypi-dependencies]
spconv-cu120 = ">=2.3.6, <3"
opencv-python = "~=4.5.1.48"
numba = "==0.49.0"
matplotlib = ">=3.7.5, <4"
shapely = "==2.0.0"
scikit-image = ">=0.19.3, <0.20"
open3d = ">=0.18.0, <0.19"
cython = ">=3.0.11, <4"
tensorboardx = ">=2.6.2.2, <3"
cumm = ">=0.5.3, <0.6"
timm = "==0.4.12"
scikit-learn = ">=1.3.2, <2"
seaborn = ">=0.13.0, <0.14"

